name: Build & Push to IPFS
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: Build Note for ${{ github.ref }}
      run: |
        echo Building ${GITHUB_REF}...

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: yarn

    - name: Install Node Dependencies
      run: yarn install

    - name: Build Web App
      run: yarn run web:build

    - name: Archive App
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist

    - name: Deploy to IPFS
      run: |
        node script/ipfs.js | tee .release-notes
      env:
        IPFS_AUTH: ${{ secrets.IPFS_AUTH }}
        IPFS_DOMAIN: ${{ secrets.IPFS_DOMAIN }}
        IPFS_HOST: ${{ secrets.IPFS_HOST }}
        IPFS_PORT: ${{ secrets.IPFS_PORT }}

    - name: Upload IPFS Release Artifact
      uses: actions/upload-artifact@v1
      with:
        name: .release
        path: .release

    - name: Add Deploy Comment
      uses: machine-learning-apps/pr-comment@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: .release-notes
      if: ${{ github.event_name == 'pull_request' }}
